### ISSUE TITLE
您好，我有一些疑问，希望能得到解答。

### ISSUE THREAD

**Issue by ty5491003** [liang2024086/code_comment_generation#1]
您好。我是西北大学的一名学生，一直在关注你们的工作，感谢你们对此做出的贡献。我有一些疑问，希望您能解答。
一。我注意到，之前在交大的网站（https://adapt.seiee.sjtu.edu.cn/CodeComment/）
下载的那份代码是带有Code_GRU所使用的数据集的，不仅包括Github上的那些repo本身，还带有那些项目经过Code_RNN处理后得到的可以直接读取用来训练GRU的数据。而现在该网站被设置跳转到本repo中，本repo的代码也进行了一定程度的更新。然而，在现在这个repo中已经找不到相关的数据了，包括Github上其他repo的数据（CodeComment_Data/Github）和对其处理过后的用于训练GRU的数据，导致现在使用本repo的代码时会报找不到文件的错误。我想知道这部分数据是因为忘记传上来了还是出于别的考虑？
二。即使是之前的那份代码，我只发现了用Jam数据训练Code_RNN和使用经Code_RNN处理过后的Github数据来训练Code_GRU两部分内容，尚未发现其中间步骤——使用Code_RNN的模型对Github数据进行处理的步骤。我想知道这部分是在哪里实现的，是否是我看遗漏了。
期待您的回复，再次感谢你们做出的贡献！

**Comment by liang2024086** [comment]
已经回复了你的邮件。

**Comment by liang2024086** [comment]
生成数据的脚本是CodeComment_Code文件夹下run_code_rnn.sh文件中的genData函数

**Comment by liang2024086** [comment]
你好，
之前的代码是有一定问题的，所以我国庆期间进行了一定修正。至于github上其他repo的数据其实是因为github检测到github上有所以传上去之后只显示一个文件夹。你可以自己到相应的repo下载源代码放到对应文件夹下即可。
数据处理的代码之前因为比较急给漏传了，所以在国庆期间进行了修正。github上的代码包含了数据生成和训练的全部代码，你可以照着github上写的方法把代码运行起来。也可以把自己的数据放到相应文件夹下进行数据生成和训练。GenClassCallGraph和GetParseTree文件夹下即为数据生成的代码。我也写了对应的运行脚本，你可以直接使用。

如果有任何问题欢迎直接问我。

梁玉鼎

----- 原始邮件 -----
发件人: "Yang Tian" <notifications@github.com>
收件人: "liang2024086/code_comment_generation" <code_comment_generation@noreply.github.com>
抄送: "Subscribed" <subscribed@noreply.github.com>
发送时间: 星期四, 2018年 11 月 01日 下午 10:55:52
主题: [liang2024086/code_comment_generation] 您好，我有一些疑问，希望能得到解答。 (#1)

您好。我是西北大学的一名学生，一直在关注你们的工作，感谢你们对此做出的贡献。我有一些疑问，希望您能解答。
一。我注意到，之前在交大的网站（https://adapt.seiee.sjtu.edu.cn/CodeComment/）
下载的那份代码是带有Code_GRU所使用的数据集的，不仅包括Github上的那些repo本身，还带有那些项目经过Code_RNN处理后得到的可以直接读取用来训练GRU的数据。而现在该网站被设置跳转到本repo中，本repo的代码也进行了一定程度的更新。然而，在现在这个repo中已经找不到相关的数据了，包括Github上其他repo的数据（CodeComment_Data/Github）和对其处理过后的用于训练GRU的数据，导致现在使用本repo的代码时会报找不到文件的错误。我想知道这部分数据是因为忘记传上来了还是出于别的考虑？
二。即使是之前的那份代码，我只发现了用Jam数据训练Code_RNN和使用经Code_RNN处理过后的Github数据来训练Code_GRU两部分内容，尚未发现其中间步骤——使用Code_RNN的模型对Github数据进行处理的步骤。我想知道这部分是在哪里实现的，是否是我看遗漏了。
期待您的回复，再次感谢你们做出的贡献！

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/liang2024086/code_comment_generation/issues/1

**Comment by liang2024086** [comment]
你好，
之前的代码是有一定问题的，所以我国庆期间进行了一定修正。至于github上其他repo的数据其实是因为github检测到github上有所以传上去之后只显示一个文件夹。你可以自己到相应的repo下载源代码放到对应文件夹下即可。
数据处理的代码之前因为比较急给漏传了，所以在国庆期间进行了修正。github上的代码包含了数据生成和训练的全部代码，你可以照着github上写的方法把代码运行起来。也可以把自己的数据放到相应文件夹下进行数据生成和训练。GenClassCallGraph和GetParseTree文件夹下即为数据生成的代码。我也写了对应的运行脚本，你可以直接使用。

**Comment by ty5491003** [comment]
我明白了，感谢您及时的回复！:laughing:

**Comment by ty5491003** [comment]
您好，我还有一点疑问，就是当我使用新数据训练GRU时，我该如何确定其中有多少个commented method？换句话说，在使用新数据运行 run_code_gru.sh时，我该如何确定后面的那几个输入参数？

**Comment by liang2024086** [comment]
这个可以你自行决定，我用的10个project的参数分别是：
Activiti 900 940 1071 800
aima-java 1000 1027 1127 800
neo4j 1000 1040 1197 800
cocos2d 1000 1040 1181 800
rhino 1000 1040 1187 800
spring-batch 1600 1650 1827 800
Smack 2100 2180 2342 800
guava 2300 2370 2530 800
jersey 2300 2350 2539 800
libgdx 2600 2650 2823 800

**Comment by ty5491003** [comment]
了解了，谢谢您及时的回复:laughing:

**Comment by ty5491003** [comment]
您好。我又来提问了:grin:
1. 我这几天尝试了增大了GRU的训练数据量（将rhino与其他项目数据合并），与您给的参数训练出的模型进行比较，发现增大后其ROUGE分数有明显提升，但这一点在论文中好像并未提及。所以我想知道，您在论文中只选用1000条（以rhino为例）数据进行训练，而不使用更多的原因是什么？
2. 我想知道，一个新项目，我该如何确定它总数据集的大小是多少呢？和 commented methods或者methods数量相关吗，我之前试验过一些，但没能得到明确的结果。希望您能解答。:laughing:

**Comment by liang2024086** [comment]
我将不同项目分开训练是因为每个项目的功能是不同的，这个可能会导致类似的函数在不同项目当中注释会出现比较大的差异。 至于训练数据集的划分你可以尝试不同的划分，我这么分只是为了保证测试数据集不要太小。

**Comment by ty5491003** [comment]
好的我明白了。谢谢您的回复。
